#-*- coding: utf-8 -*-

{
	"name": "academic",
	"version": "1.0", 
	"depends": [
		'base',
	],
	"author": "Akhmad D. Sembiring [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the academic module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/groups.xml",
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/session.xml",
		"view/course.xml",
		"view/attendee.xml",
		# "view/instructor.xml",
		# "view/user.xml",
		# "view/partner.xml",
		"report/session.xml",
		"report/course.xml",
		"report/attendee.xml",
		"report/instructor.xml",
		"report/user.xml",
		"report/partner.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}